#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "event.h"
#include "filestack.h"
#include "sddstio.h"
#include "sduti.h"

// suffixes for the auto-generted output files
#define remhytrig_suf ".nht.dst.gz"

// minimum number that in theory can be a location of a surface detector
// if any trigger position is smaller than this number then its a hybrid
// trigger
#define MIN_SD_POSID 101

class remhytrig_listOfOpt
{
  
public:
  
  char   outfile[0x400];
  char   dout[0x400];
  bool   fOverwrite;
  bool   verbose;
  
  remhytrig_listOfOpt()
  {
    sprintf(dout,"./");  // default output directory
    outfile[0] = 0;      // output file initialized
    fOverwrite = false;  // don't overwrite the output files if they exist by default
    verbose    = false;  // don't print extra stuff by default
  }
  ~remhytrig_listOfOpt() { ; }
  

  bool parseCmdLine(int argc, char **argv)
  {
    int i;
    char inBuf[0x400];
   
    if (argc <= 1)
      {
	printMan(argv[0]);
	return false;
      }

    for (i = 1; i < argc; i++)
      {
	// man
	if ( 
	    (strcmp("-h",argv[i]) == 0) || 
	    (strcmp("--h",argv[i]) == 0) ||
	    (strcmp("-help",argv[i]) == 0) ||
	    (strcmp("--help",argv[i]) == 0) ||
	    (strcmp("-?",argv[i]) == 0) ||
	    (strcmp("--?",argv[i]) == 0) ||
	    (strcmp("/?",argv[i]) == 0)
	     )
	  {
	    printMan(argv[0]);
	    return false;
	  }
      
	// list file
	else if (strcmp("-i", argv[i]) == 0)
	  {
	    FILE *fp = 0;
	    char* line = 0;
	    if ((++i >= argc) || !argv[i] || (argv[i][0] == '-'))
	      {
		fprintf(stderr,"error: -i: specify the list file\n");
		return false;
	      }
	    if (!(fp = fopen(argv[i], "r")))
	      {
		fprintf(stderr, "error: can't open %s\n", argv[i]);
		return false;
	      }
	    while (fgets(inBuf, 0x400, fp))
	      {
		if (!((line = strtok(inBuf, " \t\r\n"))) || !strlen(line))
		  continue;
		if (pushFile(line) != SUCCESS)
		  return false;
	      }
	    fclose(fp); 
	  }
	// standard input
	else if (strcmp("--tty", argv[i]) == 0)
	  {
	    char* line = 0;
	    while (fgets(inBuf, 0x400, stdin))
	      {
		if (!((line = strtok(inBuf, " \t\r\n"))) || !strlen(line))
		  continue;
		if (pushFile(line) != SUCCESS)
		  return false;
	      }
	  }
	// output directory
	else if (strcmp("-o", argv[i]) == 0)
	  {
	    if ((++i >= argc) || !argv[i] || (argv[i][0] == '-'))
	      {
		fprintf(stderr, "error: specify the output directory\n");
		return false;
	      }
	    else
	      sscanf(argv[i], "%1023s", dout);
	  }
	// signle output file
	else if (strcmp("-o1f", argv[i]) == 0)
	  {
	    if ((++i >= argc) || !argv[i] || (argv[i][0] == '-'))
	      {
		fprintf(stderr, "error: specify the output file\n");
		return false;
	      }
	    else
	      sscanf(argv[i], "%1023s", outfile);
	  }
	// force overwrite mode
	else if (strcmp("-f", argv[i]) == 0)
	  fOverwrite = true;
	
	// verbose mode
	else if (strcmp("-v", argv[i]) == 0)
	  verbose = true;
	// all arguments w/o the '-' switch should be the input files
	else if (argv[i][0] != '-')
	  {
	    if (pushFile(argv[i]) != SUCCESS)
	      return false;
	  }
	else
	  {
	    fprintf(stderr, "error: %s: unrecognized option\n", argv[i]);
	    return false;
	  }
      }
    if (countFiles()==0)
      {
	fprintf(stderr,"error: no input files\n");
	return false;
      }
    return true;
  }
 
  void printMan(char* progName)
  {
    fprintf(stderr,"\nRemove all events that are due to the hybrid trigger alone, so that the data behaves \n");
    fprintf(stderr,"according to the usual SD trigger\n");
    fprintf(stderr,"all events are required to have tasdcalibev bank; otherwise they are skipped\n");
    fprintf(stderr,"\nusage: %s [in_file1 ...] and/or -i [list file]  -o [output directory]\n",progName);
    fprintf(stderr,"pass input dst file names as arguments without any prefixes or switches\n");
    fprintf(stderr, "-i <string>    : specify the want file (with dst files)\n");
    fprintf(stderr, "--tty <string> : or get input dst file names from stdin\n");
    fprintf(stderr, "-o <string>    : specify the output directory; output files are auto-generated by adding '%s'\n",
	    remhytrig_suf);
    fprintf(stderr, "                 suffix to input file basenames and are put to the output directory; default is %s\n",
	    dout);
    fprintf(stderr, "-o1f <string   : specify a single output file, overrides the -o option\n");
    fprintf(stderr, "-f             : overwrite the output files if they exist\n");
    fprintf(stderr, "-v             : verbose mode\n");
    fprintf(stderr,"\n");
  }
  
};


int main(int argc, char *argv[])
{
  
  char  oflgen[0x400]; // stores output files that are auto-generated by directory and suffix substitution
  
  // cmd line options
  remhytrig_listOfOpt opt;
  if (!opt.parseCmdLine(argc,argv))
    return 2;
  
  // dst iterator
  sddstio_class dstio(opt.verbose);
  
 
  char* infile = 0;
  int nread=0;
  int nrem=0;
  int nwritten=0;
  while((infile=pullFile()))
    {
      if(!dstio.openDSTinFile(infile))
	return 2;
      
  
      while(dstio.readEvent())
	{
	  nread++;
	  
	  // throw out any purely hybrid triggers
	  if (dstio.haveBank(TASDCALIBEV_BANKID,opt.verbose) && tasdcalibev_.trgPos < MIN_SD_POSID)
	    {
	      nrem++;
	      continue;
	    }
	  // write out the event
	  if (!dstio.outFileOpen())
	    {
	      if (opt.outfile[0])
		{
		  if(!dstio.openDSToutFile(opt.outfile,opt.fOverwrite))
		    return 2;
		}
	      else
		{
		  // To produce the output file name with correct suffix.
		  if (SDIO::makeOutFileName(infile,opt.dout,(char* )remhytrig_suf,oflgen) != 1)
		    return 2;
		  if (!dstio.openDSToutFile(oflgen,opt.fOverwrite))
		    return 2;
		}
	    }
	  dstio.writeEvent();
	  nwritten++;
	}
      dstio.closeDSTinFile();
      if(!opt.outfile[0])
	dstio.closeDSToutFile();
    }
  
  // finilize the dst output file
  if(dstio.outFileOpen())
    dstio.closeDSToutFile();
  
  fprintf(stdout,"remhytrig_events_read    : %d\n", nread);
  fprintf(stdout,"remhytrig_events_written : %d\n", nwritten);
  fprintf(stdout,"remhytrig_events_removed : %d\n", nrem);
  
  return 0; 
}

