input_dim: 6
hidden_dim: 32
latent_dim: 64
batch_size: 400
lr: 1e-4
epoches: 200

#for masking in dataloader
padding_value: -11.0
stop_token: -10.0
start_token: 10.0

use_mask: False
PATH: '../../Models_VAE/model_new_decoder_add_mask_not_loss'
show_index:
  - 10
  - 20
  - 30