mode: Latent
input_dim: 6
hidden_dim: 128
latent_dim: 16
num_layers: 10
batch_size: 150
lr: 1e-4
epoches: 100
lstm2: False
#data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_q4_14yr_e1_0110_excl_sat_F_excl_geo_F.h5'
# data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_fe_q4_e1_0110_excl_sat_F_excl_geo_F.h5'
data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_photon_0001_excl_sat_F_excl_geo_F.h5'
#for masking in dataloader
padding_value: -11.0
stop_token: -10.0
start_token: hard_v1
koef_KL: 0.0
koef_DL: 0.1
koef_mass: 0.0
paticles:
  train:
    - pr
    # - photon
  test:
    - pr
    - photon

koef_loss: [1,1,0,1,1,1]
exp: AutoEncoder
use_mask: True
PATH: Encoder_2Transformer_10layers_CLS_CONT_BUT_128HID_EQUAL
save_model_path: /home/rfit/Telescope_Array/phd_work/Models/AutoEncoder
show_index:
  - 10
  - 20
  - 30
write_param:
  # - 'hidden_dim'
  - 'paticles'
chpt: None
# chpt: /home/rfit/Telescope_Array/phd_work/Models/AutoEncoder/Encoder_2Transformer_CLS/best