#ifdef __CINT__
using namespace std;
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class vector <Byte_t>;
#pragma link C++ class vector <Char_t>;
#pragma link C++ class vector <Short_t>;
#pragma link C++ class vector <Int_t>;
#pragma link C++ class vector <Float_t>;
#pragma link C++ class vector <Double_t>;
#pragma link C++ class vector <vector <Byte_t> >;
#pragma link C++ class vector <vector <vector <Byte_t> > >;
#pragma link C++ class vector <vector <Char_t> >;
#pragma link C++ class vector <vector <vector <Char_t> > >;
#pragma link C++ class vector <vector <Short_t> >;
#pragma link C++ class vector <vector <vector <Short_t> > >;
#pragma link C++ class vector <vector <Int_t> >;
#pragma link C++ class vector <vector <vector <Int_t> > >;
#pragma link C++ class vector <vector <Float_t> >;
#pragma link C++ class vector <vector <vector <Float_t> > >;
#pragma link C++ class vector <vector <Double_t> >;
#pragma link C++ class vector <vector <vector <Double_t> > >;
#pragma link C++ class dstbank_class;
#pragma link C++ class talex00_class;
#pragma link C++ class rusdraw_class;
#pragma link C++ class rusdmc_class;
#pragma link C++ class rusdmc1_class;
#pragma link C++ class showlib_class;
#pragma link C++ class bsdinfo_class;
#pragma link C++ class sdtrgbk_class;
#pragma link C++ class SDEventSubData_class;
#pragma link C++ class vector <SDEventSubData_class>;
#pragma link C++ class tasdevent_class;
#pragma link C++ class SDCalibHostData_class;
#pragma link C++ class SDCalibSubData_class;
#pragma link C++ class SDCalibWeatherData_class;
#pragma link C++ class vector <SDCalibHostData_class>;
#pragma link C++ class vector <SDCalibSubData_class>;
#pragma link C++ class vector <SDCalibWeatherData_class>;
#pragma link C++ class tasdcalib_class;
#pragma link C++ class SDCalibevData_class;
#pragma link C++ class SDCalibevWeatherData_class;
#pragma link C++ class SDCalibevSimInfo_class;
#pragma link C++ class vector <SDCalibevData_class>;
#pragma link C++ class vector <SDCalibevWeatherData_class>;
#pragma link C++ class tasdcalibev_class;
#pragma link C++ class rufptn_class;
#pragma link C++ class rusdgeom_class;
#pragma link C++ class rufldf_class;
#pragma link C++ class etrack_class;
#pragma link C++ class atmpar_class;
#pragma link C++ class fdraw_class;
#pragma link C++ class brraw_class;
#pragma link C++ class lrraw_class;
#pragma link C++ class fdplane_class;
#pragma link C++ class brplane_class;
#pragma link C++ class lrplane_class;
#pragma link C++ class fdprofile_class;
#pragma link C++ class brprofile_class;
#pragma link C++ class lrprofile_class;
#pragma link C++ class fdtubeprofile_class;
#pragma link C++ class brtubeprofile_class;
#pragma link C++ class lrtubeprofile_class;
#pragma link C++ class hbar_class;
#pragma link C++ class hraw1_class;
#pragma link C++ class mc04_class;
#pragma link C++ class mcraw_class;
#pragma link C++ class stps2_class;
#pragma link C++ class stpln_class;
#pragma link C++ class hctim_class;
#pragma link C++ class hcbin_class;
#pragma link C++ class prfc_class;
#pragma link C++ class fdatmos_param_class;
#pragma link C++ class gdas_class;
#endif
