mode: Latent
input_dim: 6
hidden_dim: 512
latent_dim: 8
batch_size: 2000
lr: 1e-3
epoches: 100
lstm2: False
#data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_q4_14yr_e1_0110_excl_sat_F_excl_geo_F.h5'
# data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_fe_q4_e1_0110_excl_sat_F_excl_geo_F.h5'
data_path: '/home3/rfit/Telescope_Array/phd_work/data/normed/pr_photon_0001_excl_sat_F_excl_geo_F.h5'
#for masking in dataloader
padding_value: -11.0
stop_token: -10.0
start_token: hard_v1
koef_KL: 0.0
koef_DL: 0.1
koef_mass: 0.1
paticles:
  train:
    - pr
    - photon
  test:
    - pr
    - photon


koef_loss: [1,1,0,1,1,1]
exp: lat8
use_mask: True
PATH: 'test_particles/predict_part'
show_index:
  - 10
  - 20
  - 30
used_model: 'TransformerClassificationModel'
encoder_path: /home/rfit/Telescope_Array/phd_work/Models/AutoEncoder/Proton_train_lat=8/best
save_model_path: /home/rfit/Telescope_Array/phd_work/Models/Classification
write_param:
  - 'latent_dim'
  # - 'hidden_dim'
  - 'paticles'
chpt: None
# chpt: /home/rfit/Telescope_Array/phd_work/src/train_VAE/test_particles/Pr_latent_64latent_dim=64;_paticles=['pr'];_/best