//
// File generated by rootcint at Wed Sep  6 14:38:47 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dInetdIminusdIhomedIgrishadItadIsdanalysisdIgldffitterdIgldffitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "gldffitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void gldffitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_gldffitter(void *p = 0);
   static void *newArray_gldffitter(Long_t size, void *p);
   static void delete_gldffitter(void *p);
   static void deleteArray_gldffitter(void *p);
   static void destruct_gldffitter(void *p);
   static void streamer_gldffitter(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::gldffitter*)
   {
      ::gldffitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::gldffitter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("gldffitter", ::gldffitter::Class_Version(), "/net/minus/home/grisha/ta/sdanalysis/gldffitter/gldffitter.h", 53,
                  typeid(::gldffitter), DefineBehavior(ptr, ptr),
                  &::gldffitter::Dictionary, isa_proxy, 0,
                  sizeof(::gldffitter) );
      instance.SetNew(&new_gldffitter);
      instance.SetNewArray(&newArray_gldffitter);
      instance.SetDelete(&delete_gldffitter);
      instance.SetDeleteArray(&deleteArray_gldffitter);
      instance.SetDestructor(&destruct_gldffitter);
      instance.SetStreamerFunc(&streamer_gldffitter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::gldffitter*)
   {
      return GenerateInitInstanceLocal((::gldffitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::gldffitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *gldffitter::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *gldffitter::Class_Name()
{
   return "gldffitter";
}

//______________________________________________________________________________
const char *gldffitter::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::gldffitter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int gldffitter::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::gldffitter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void gldffitter::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::gldffitter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *gldffitter::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::gldffitter*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void gldffitter::Streamer(TBuffer &R__b)
{
   // Stream an object of class gldffitter.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.ReadStaticArray((int*)sds_hit);
      R__b >> gMinuit;
      R__b.ReadStaticArray((double*)sdorigin_xy);
      R__b >> gTrsdVsR;
      R__b >> gTrsdVsS;
      R__b >> gTvsU;
      R__b >> gRhoVsS;
      R__b >> gRhoRsdVsS;
      R__b >> nfitsds;
      R__b >> nldffitsds;
      R__b >> ntfitsds;
      R__b >> nfitpts;
      R__b.ReadStaticArray((int*)fxxyy);
      R__b.ReadStaticArray((int*)fpflag);
      R__b.ReadStaticArray((double*)fX);
      R__b.ReadStaticArray((double*)ft);
      R__b.ReadStaticArray((double*)fdt);
      R__b.ReadStaticArray((double*)frho);
      R__b.ReadStaticArray((double*)fdrho);
      R__b >> hTrsdS;
      R__b >> pTrsdS;
      R__b >> hTrsdRho;
      R__b >> pTrsdRho;
      R__b >> theta;
      R__b >> phi;
      R__b >> dtheta;
      R__b >> dphi;
      R__b.ReadStaticArray((double*)R);
      R__b.ReadStaticArray((double*)dR);
      R__b >> T0;
      R__b >> dT0;
      R__b >> S;
      R__b >> dS;
      R__b >> ldfFun;
      R__b >> s600;
      R__b >> s600_0;
      R__b >> s800;
      R__b >> s800_0;
      R__b >> aenergy;
      R__b >> energy;
      R__b >> log10en;
      R__b >> chi2;
      R__b >> ndof;
      R__b >> theta_old;
      R__b >> phi_old;
      R__b.ReadStaticArray((double*)R_old);
      R__b >> T0_old;
      R__b >> S_old;
      R__b.CheckByteCount(R__s, R__c, gldffitter::IsA());
   } else {
      R__c = R__b.WriteVersion(gldffitter::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.WriteArray((int*)sds_hit, 672);
      R__b << gMinuit;
      R__b.WriteArray(sdorigin_xy, 2);
      R__b << gTrsdVsR;
      R__b << gTrsdVsS;
      R__b << gTvsU;
      R__b << gRhoVsS;
      R__b << gRhoRsdVsS;
      R__b << nfitsds;
      R__b << nldffitsds;
      R__b << ntfitsds;
      R__b << nfitpts;
      R__b.WriteArray(fxxyy, 1024);
      R__b.WriteArray(fpflag, 1024);
      R__b.WriteArray((double*)fX, 3072);
      R__b.WriteArray(ft, 1024);
      R__b.WriteArray(fdt, 1024);
      R__b.WriteArray(frho, 1024);
      R__b.WriteArray(fdrho, 1024);
      R__b << (TObject*)hTrsdS;
      R__b << (TObject*)pTrsdS;
      R__b << (TObject*)hTrsdRho;
      R__b << (TObject*)pTrsdRho;
      R__b << theta;
      R__b << phi;
      R__b << dtheta;
      R__b << dphi;
      R__b.WriteArray(R, 2);
      R__b.WriteArray(dR, 2);
      R__b << T0;
      R__b << dT0;
      R__b << S;
      R__b << dS;
      R__b << ldfFun;
      R__b << s600;
      R__b << s600_0;
      R__b << s800;
      R__b << s800_0;
      R__b << aenergy;
      R__b << energy;
      R__b << log10en;
      R__b << chi2;
      R__b << ndof;
      R__b << theta_old;
      R__b << phi_old;
      R__b.WriteArray(R_old, 2);
      R__b << T0_old;
      R__b << S_old;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void gldffitter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class gldffitter.
      TClass *R__cl = ::gldffitter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sds_hit[24][28]", sds_hit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gMinuit", &gMinuit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sdorigin_xy[2]", sdorigin_xy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTrsdVsR", &gTrsdVsR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTrsdVsS", &gTrsdVsS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTvsU", &gTvsU);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gRhoVsS", &gRhoVsS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gRhoRsdVsS", &gRhoRsdVsS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nfitsds", &nfitsds);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nldffitsds", &nldffitsds);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ntfitsds", &ntfitsds);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nfitpts", &nfitpts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fxxyy[1024]", fxxyy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpflag[1024]", fpflag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fX[1024][3]", fX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ft[1024]", ft);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fdt[1024]", fdt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "frho[1024]", frho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fdrho[1024]", fdrho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hTrsdS", &hTrsdS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pTrsdS", &pTrsdS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hTrsdRho", &hTrsdRho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pTrsdRho", &pTrsdRho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta", &theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi", &phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtheta", &dtheta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dphi", &dphi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "R[2]", R);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dR[2]", dR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T0", &T0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dT0", &dT0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "S", &S);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dS", &dS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ldfFun", &ldfFun);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s600", &s600);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s600_0", &s600_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s800", &s800);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s800_0", &s800_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "aenergy", &aenergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "log10en", &log10en);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2", &chi2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndof", &ndof);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta_old", &theta_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi_old", &phi_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "R_old[2]", R_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T0_old", &T0_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "S_old", &S_old);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_gldffitter(void *p) {
      return  p ? new(p) ::gldffitter : new ::gldffitter;
   }
   static void *newArray_gldffitter(Long_t nElements, void *p) {
      return p ? new(p) ::gldffitter[nElements] : new ::gldffitter[nElements];
   }
   // Wrapper around operator delete
   static void delete_gldffitter(void *p) {
      delete ((::gldffitter*)p);
   }
   static void deleteArray_gldffitter(void *p) {
      delete [] ((::gldffitter*)p);
   }
   static void destruct_gldffitter(void *p) {
      typedef ::gldffitter current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_gldffitter(TBuffer &buf, void *obj) {
      ((::gldffitter*)obj)->::gldffitter::Streamer(buf);
   }
} // end of namespace ROOT for class ::gldffitter

/********************************************************
* /net/minus/home/grisha/ta/sdanalysis/gldffitter/gldffitterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablegldffitterDict();

extern "C" void G__set_cpp_environmentgldffitterDict() {
  G__cpp_reset_tagtablegldffitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevgldffitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* gldffitter */
static int G__gldffitterDict_496_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((gldffitter*) G__getstructoffset())->loadVariables((rusdraw_class*) G__int(libp->para[0]), (rufptn_class*) G__int(libp->para[1])
, (rusdgeom_class*) G__int(libp->para[2]), (rufldf_class*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->xycoor((Int_t) G__int(libp->para[0]), (Int_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((gldffitter*) G__getstructoffset())->clean((Double_t) G__double(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((gldffitter*) G__getstructoffset())->clean((Double_t) G__double(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((gldffitter*) G__getstructoffset())->clean());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->calcRsd(
(Int_t) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])
, (Double_t*) G__int(libp->para[2]), (Double_t*) G__int(libp->para[3])
, (Double_t*) G__int(libp->para[4]), (Double_t*) G__int(libp->para[5])
, (Double_t*) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->cleanRsd();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->fillRsd();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 103, (long) ((gldffitter*) G__getstructoffset())->Ifit((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((gldffitter*) G__getstructoffset())->Ifit());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   gldffitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new gldffitter[n];
     } else {
       p = new((void*) gvp) gldffitter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new gldffitter;
     } else {
       p = new((void*) gvp) gldffitter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->compVars();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) gldffitter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) gldffitter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) gldffitter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      gldffitter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((gldffitter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) gldffitter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) gldffitter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) gldffitter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__gldffitterDict_496_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) gldffitter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__gldffitterDict_496_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   gldffitter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new gldffitter(*(gldffitter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef gldffitter G__Tgldffitter;
static int G__gldffitterDict_496_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (gldffitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((gldffitter*) (soff+(sizeof(gldffitter)*i)))->~G__Tgldffitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (gldffitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((gldffitter*) (soff))->~G__Tgldffitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__gldffitterDict_496_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   gldffitter* dest = (gldffitter*) G__getstructoffset();
   *dest = *(gldffitter*) libp->para[0].ref;
   const gldffitter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* gldffitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncgldffitterDict {
 public:
  G__Sizep2memfuncgldffitterDict(): p(&G__Sizep2memfuncgldffitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncgldffitterDict::*p)();
};

size_t G__get_sizep2memfuncgldffitterDict()
{
  G__Sizep2memfuncgldffitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancegldffitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter))) {
     gldffitter *G__Lderived;
     G__Lderived=(gldffitter*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter),G__get_linked_tagnum(&G__gldffitterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablegldffitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Int_t> >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Int_t> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Double_t> >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Double_t> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Short_t> >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<short,allocator<short> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Short_t> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Char_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEcharcOallocatorlEchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDEventSubData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Float_t> >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibHostData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibSubData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibWeatherData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevWeatherData_class>",117,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__gldffitterDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* gldffitter */
static void G__setup_memvargldffitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter));
   { gldffitter *p; p=(gldffitter*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->sds_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"sds_hit[24][28]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gMinuit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TMinuit),-1,-1,1,"gMinuit=",0,"Minuit fitter");
   G__memvar_setup((void*)((long)(&p->sdorigin_xy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"sdorigin_xy[2]=",0,"Position of SD origin with respect to CLF in CLF frame");
   G__memvar_setup((void*)((long)(&p->gTrsdVsR)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TGraphErrors),-1,-1,1,"gTrsdVsR=",0,"Time fit residual vs distance from core in ground plane");
   G__memvar_setup((void*)((long)(&p->gTrsdVsS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TGraphErrors),-1,-1,1,"gTrsdVsS=",0,"Time fit residual vs distance from shower axis");
   G__memvar_setup((void*)((long)(&p->gTvsU)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TGraphErrors),-1,-1,1,"gTvsU=",0,"Time vs distance along the shower axis in ground plane");
   G__memvar_setup((void*)((long)(&p->gRhoVsS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TGraphErrors),-1,-1,1,"gRhoVsS=",0,"Charge Density [VEM/m^2] vs Distance from Shower axis");
   G__memvar_setup((void*)((long)(&p->gRhoRsdVsS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TGraphErrors),-1,-1,1,"gRhoRsdVsS=",0,"Charge [VEM/m^2] vs Distance from Shower axis");
   G__memvar_setup((void*)((long)(&p->nfitsds)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nfitsds=",0,"Number SDs used in fitting (including zero charge) ");
   G__memvar_setup((void*)((long)(&p->nldffitsds)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nldffitsds=",0,"Number of non-zero charge SDs used in LDF");
   G__memvar_setup((void*)((long)(&p->ntfitsds)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ntfitsds=",0,"Number of SDs used in time fitting");
   G__memvar_setup((void*)((long)(&p->nfitpts)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nfitpts=",0,"Number of effective fit points which goes into calculation of ndof");
   G__memvar_setup((void*)((long)(&p->fxxyy)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fxxyy[1024]=",0,"lid of counters in the fit");
   G__memvar_setup((void*)((long)(&p->fpflag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fpflag[1024]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fX)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fX[1024][3]=",0,"Position used in fitting");
   G__memvar_setup((void*)((long)(&p->ft)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ft[1024]=",0,"Time used in fitting");
   G__memvar_setup((void*)((long)(&p->fdt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fdt[1024]=",0,"Time resolution used in fitting");
   G__memvar_setup((void*)((long)(&p->frho)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"frho[1024]=",0,"Charge density used in fitting");
   G__memvar_setup((void*)((long)(&p->fdrho)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fdrho[1024]=",0,"Charge density fluctuation used in fitting");
   G__memvar_setup((void*)((long)(&p->hTrsdS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TH2F),-1,-1,1,"hTrsdS=",0,"Residuals vs s scatter plot");
   G__memvar_setup((void*)((long)(&p->pTrsdS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TProfile),-1,-1,1,"pTrsdS=",0,"Residuals vs s profile plot");
   G__memvar_setup((void*)((long)(&p->hTrsdRho)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TH2F),-1,-1,1,"hTrsdRho=",0,"Residuals vs rho scatter plot");
   G__memvar_setup((void*)((long)(&p->pTrsdRho)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TProfile),-1,-1,1,"pTrsdRho=",0,"Residuals vs rho profile plot");
   G__memvar_setup((void*)((long)(&p->theta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"phi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtheta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dtheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dphi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"R[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dR)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dR[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dT0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dT0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->S)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"S=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dS)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dS=",0,"LDF scaling constant");
   G__memvar_setup((void*)((long)(&p->ldfFun)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TF1),-1,-1,1,"ldfFun=",0,"LDF curve, to show on the plots");
   G__memvar_setup((void*)((long)(&p->s600)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"s600=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s600_0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"s600_0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s800)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"s800=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s800_0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"s800_0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->aenergy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"aenergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->log10en)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"log10en=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chi2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"chi2=",0,"FCN at its minimum");
   G__memvar_setup((void*)((long)(&p->ndof)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndof=",0,"number of fit pts minus number of fit params");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"theta_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"phi_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"R_old[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"T0_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"S_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__gldffitterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvargldffitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgldffitter(void) {
   /* gldffitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter));
   G__memfunc_setup("loadVariables",1337,G__gldffitterDict_496_0_1, 103, -1, -1, 0, 4, 1, 1, 0, 
"U 'rusdraw_class' - 0 - rusdraw1 U 'rufptn_class' - 0 - rufptn1 "
"U 'rusdgeom_class' - 0 - rusdgeom1 U 'rufldf_class' - 0 - rufldf1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("xycoor",676,G__gldffitterDict_496_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - xxyy I - 'Int_t' 0 - xy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clean",515,G__gldffitterDict_496_0_3, 105, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '3.0' deltaChi2 g - - 0 'true' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("calcRsd",700,G__gldffitterDict_496_0_4, 121, -1, -1, 0, 7, 1, 1, 0, 
"i - 'Int_t' 0 - isds D - 'Double_t' 0 - trsd "
"D - 'Double_t' 0 - terr D - 'Double_t' 0 - chrgdens "
"D - 'Double_t' 0 - chrgdenserr D - 'Double_t' 0 - rcore "
"D - 'Double_t' 0 - score", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("cleanRsd",812,G__gldffitterDict_496_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fillRsd",720,G__gldffitterDict_496_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Ifit",396,G__gldffitterDict_496_0_7, 103, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("gldffitter",1067,G__gldffitterDict_496_0_8, 105, G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compVars",843,G__gldffitterDict_496_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("save_fpars",1066,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "to save fit parameters in a buffer", (void*) NULL, 0);
   G__memfunc_setup("restore_fpars",1407,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "to restore the fit parameters, so that they can be used as starting values", (void*) NULL, 0);
   G__memfunc_setup("save_fitinfo",1277,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "saves fitting info (data points corresponding to non-zero SDs in LDF & time fitting parts)", (void*) NULL, 0);
   G__memfunc_setup("calc_results",1284,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("print_results",1438,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__gldffitterDict_496_0_15, 85, G__get_linked_tagnum(&G__gldffitterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&gldffitter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__gldffitterDict_496_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&gldffitter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__gldffitterDict_496_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&gldffitter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__gldffitterDict_496_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&gldffitter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__gldffitterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__gldffitterDict_496_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__gldffitterDict_496_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&gldffitter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__gldffitterDict_496_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&gldffitter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__gldffitterDict_496_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&gldffitter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__gldffitterDict_496_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&gldffitter::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("gldffitter", 1067, G__gldffitterDict_496_0_27, (int) ('i'), G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter), -1, 0, 1, 1, 1, 0, "u 'gldffitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~gldffitter", 1193, G__gldffitterDict_496_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__gldffitterDict_496_0_29, (int) ('u'), G__get_linked_tagnum(&G__gldffitterDictLN_gldffitter), -1, 1, 1, 1, 1, 0, "u 'gldffitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncgldffitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalgldffitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcgldffitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__gldffitterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEcharcOallocatorlEchargRsPgR = { "vector<char,allocator<char> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TMinuit = { "TMinuit" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_rusdraw_class = { "rusdraw_class" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR = { "vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR = { "vector<SDEventSubData_class,allocator<SDEventSubData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDEventSubData_class,allocator<SDEventSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR = { "vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR = { "vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR = { "vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR = { "vector<SDCalibevData_class,allocator<SDCalibevData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevData_class,allocator<SDCalibevData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR = { "vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_rufptn_class = { "rufptn_class" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_rusdgeom_class = { "rusdgeom_class" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_rufldf_class = { "rufldf_class" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__gldffitterDictLN_TProfile = { "TProfile" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__gldffitterDictLN_gldffitter = { "gldffitter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablegldffitterDict() {
  G__gldffitterDictLN_TClass.tagnum = -1 ;
  G__gldffitterDictLN_TBuffer.tagnum = -1 ;
  G__gldffitterDictLN_TMemberInspector.tagnum = -1 ;
  G__gldffitterDictLN_TObject.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEcharcOallocatorlEchargRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_TMinuit.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_rusdraw_class.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR.tagnum = -1 ;
  G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__gldffitterDictLN_rufptn_class.tagnum = -1 ;
  G__gldffitterDictLN_rusdgeom_class.tagnum = -1 ;
  G__gldffitterDictLN_rufldf_class.tagnum = -1 ;
  G__gldffitterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__gldffitterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__gldffitterDictLN_TF1.tagnum = -1 ;
  G__gldffitterDictLN_TGraphErrors.tagnum = -1 ;
  G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__gldffitterDictLN_TProfile.tagnum = -1 ;
  G__gldffitterDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__gldffitterDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__gldffitterDictLN_TH2F.tagnum = -1 ;
  G__gldffitterDictLN_gldffitter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablegldffitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEcharcOallocatorlEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TMinuit);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_rusdraw_class);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_rufptn_class);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_rusdgeom_class);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_rufldf_class);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TF1);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TProfile);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__gldffitterDictLN_TH2F);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__gldffitterDictLN_gldffitter),sizeof(gldffitter),-1,29952,(char*)NULL,G__setup_memvargldffitter,G__setup_memfuncgldffitter);
}
extern "C" void G__cpp_setupgldffitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupgldffitterDict()");
  G__set_cpp_environmentgldffitterDict();
  G__cpp_setup_tagtablegldffitterDict();

  G__cpp_setup_inheritancegldffitterDict();

  G__cpp_setup_typetablegldffitterDict();

  G__cpp_setup_memvargldffitterDict();

  G__cpp_setup_memfuncgldffitterDict();
  G__cpp_setup_globalgldffitterDict();
  G__cpp_setup_funcgldffitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncgldffitterDict();
  return;
}
class G__cpp_setup_initgldffitterDict {
  public:
    G__cpp_setup_initgldffitterDict() { G__add_setup_func("gldffitterDict",(G__incsetup)(&G__cpp_setupgldffitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initgldffitterDict() { G__remove_setup_func("gldffitterDict"); }
};
G__cpp_setup_initgldffitterDict G__cpp_setup_initializergldffitterDict;

