//
// File generated by rootcint at Wed Sep  6 14:38:35 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dInetdIminusdIhomedIgrishadItadIsdanalysisdIsdgeomfitterdIsdgeomfitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "sdgeomfitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void sdgeomfitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_sdgeomfitter(void *p = 0);
   static void *newArray_sdgeomfitter(Long_t size, void *p);
   static void delete_sdgeomfitter(void *p);
   static void deleteArray_sdgeomfitter(void *p);
   static void destruct_sdgeomfitter(void *p);
   static void streamer_sdgeomfitter(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::sdgeomfitter*)
   {
      ::sdgeomfitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::sdgeomfitter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("sdgeomfitter", ::sdgeomfitter::Class_Version(), "/net/minus/home/grisha/ta/sdanalysis/sdgeomfitter/sdgeomfitter.h", 56,
                  typeid(::sdgeomfitter), DefineBehavior(ptr, ptr),
                  &::sdgeomfitter::Dictionary, isa_proxy, 0,
                  sizeof(::sdgeomfitter) );
      instance.SetNew(&new_sdgeomfitter);
      instance.SetNewArray(&newArray_sdgeomfitter);
      instance.SetDelete(&delete_sdgeomfitter);
      instance.SetDeleteArray(&deleteArray_sdgeomfitter);
      instance.SetDestructor(&destruct_sdgeomfitter);
      instance.SetStreamerFunc(&streamer_sdgeomfitter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::sdgeomfitter*)
   {
      return GenerateInitInstanceLocal((::sdgeomfitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::sdgeomfitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *sdgeomfitter::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *sdgeomfitter::Class_Name()
{
   return "sdgeomfitter";
}

//______________________________________________________________________________
const char *sdgeomfitter::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::sdgeomfitter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int sdgeomfitter::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::sdgeomfitter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void sdgeomfitter::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::sdgeomfitter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *sdgeomfitter::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::sdgeomfitter*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void sdgeomfitter::Streamer(TBuffer &R__b)
{
   // Stream an object of class sdgeomfitter.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> gMinuit;
      R__b.ReadStaticArray((double*)sdorigin_xy);
      R__b >> gTrsdVsR;
      R__b >> gTrsdVsS;
      R__b >> gTvsU;
      R__b >> gQvsS;
      R__b >> ngpts;
      R__b.ReadStaticArray((int*)goodpts);
      R__b >> hRsdS;
      R__b >> pRsdS;
      R__b >> hRsdRho;
      R__b >> pRsdRho;
      R__b >> theta;
      R__b >> phi;
      R__b >> dtheta;
      R__b >> dphi;
      R__b.ReadStaticArray((double*)R);
      R__b.ReadStaticArray((double*)dR);
      R__b >> T0;
      R__b >> dT0;
      R__b >> a;
      R__b >> da;
      R__b >> linsleyA;
      R__b >> chi2;
      R__b >> ndof;
      R__b >> theta_old;
      R__b >> phi_old;
      R__b.ReadStaticArray((double*)R_old);
      R__b >> T0_old;
      R__b.CheckByteCount(R__s, R__c, sdgeomfitter::IsA());
   } else {
      R__c = R__b.WriteVersion(sdgeomfitter::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << gMinuit;
      R__b.WriteArray(sdorigin_xy, 2);
      R__b << gTrsdVsR;
      R__b << gTrsdVsS;
      R__b << gTvsU;
      R__b << gQvsS;
      R__b << ngpts;
      R__b.WriteArray(goodpts, 1024);
      R__b << (TObject*)hRsdS;
      R__b << (TObject*)pRsdS;
      R__b << (TObject*)hRsdRho;
      R__b << (TObject*)pRsdRho;
      R__b << theta;
      R__b << phi;
      R__b << dtheta;
      R__b << dphi;
      R__b.WriteArray(R, 2);
      R__b.WriteArray(dR, 2);
      R__b << T0;
      R__b << dT0;
      R__b << a;
      R__b << da;
      R__b << linsleyA;
      R__b << chi2;
      R__b << ndof;
      R__b << theta_old;
      R__b << phi_old;
      R__b.WriteArray(R_old, 2);
      R__b << T0_old;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void sdgeomfitter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class sdgeomfitter.
      TClass *R__cl = ::sdgeomfitter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gMinuit", &gMinuit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sdorigin_xy[2]", sdorigin_xy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTrsdVsR", &gTrsdVsR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTrsdVsS", &gTrsdVsS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gTvsU", &gTvsU);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gQvsS", &gQvsS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ngpts", &ngpts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "goodpts[1024]", goodpts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hRsdS", &hRsdS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pRsdS", &pRsdS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*hRsdRho", &hRsdRho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pRsdRho", &pRsdRho);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta", &theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi", &phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtheta", &dtheta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dphi", &dphi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "R[2]", R);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dR[2]", dR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T0", &T0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dT0", &dT0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "a", &a);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "da", &da);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "linsleyA", &linsleyA);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2", &chi2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndof", &ndof);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta_old", &theta_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi_old", &phi_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "R_old[2]", R_old);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T0_old", &T0_old);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_sdgeomfitter(void *p) {
      return  p ? new(p) ::sdgeomfitter : new ::sdgeomfitter;
   }
   static void *newArray_sdgeomfitter(Long_t nElements, void *p) {
      return p ? new(p) ::sdgeomfitter[nElements] : new ::sdgeomfitter[nElements];
   }
   // Wrapper around operator delete
   static void delete_sdgeomfitter(void *p) {
      delete ((::sdgeomfitter*)p);
   }
   static void deleteArray_sdgeomfitter(void *p) {
      delete [] ((::sdgeomfitter*)p);
   }
   static void destruct_sdgeomfitter(void *p) {
      typedef ::sdgeomfitter current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_sdgeomfitter(TBuffer &buf, void *obj) {
      ((::sdgeomfitter*)obj)->::sdgeomfitter::Streamer(buf);
   }
} // end of namespace ROOT for class ::sdgeomfitter

/********************************************************
* /net/minus/home/grisha/ta/sdanalysis/sdgeomfitter/sdgeomfitterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablesdgeomfitterDict();

extern "C" void G__set_cpp_environmentsdgeomfitterDict() {
  G__cpp_reset_tagtablesdgeomfitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevsdgeomfitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* sdgeomfitter */
static int G__sdgeomfitterDict_476_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((sdgeomfitter*) G__getstructoffset())->loadVariables_stclust((rufptn_class*) G__int(libp->para[0]), (rusdgeom_class*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->xycoor((Int_t) G__int(libp->para[0]), (Int_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((sdgeomfitter*) G__getstructoffset())->cleanClust((Double_t) G__double(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((sdgeomfitter*) G__getstructoffset())->cleanClust((Double_t) G__double(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((sdgeomfitter*) G__getstructoffset())->cleanClust());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->calcRsd((Int_t) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1])
, (Double_t*) G__int(libp->para[2]), (Double_t*) G__int(libp->para[3])
, (Double_t*) G__int(libp->para[4]), (Double_t*) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->cleanRsd();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->fillRsd();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 103, (long) ((sdgeomfitter*) G__getstructoffset())->Ifit((Int_t) G__int(libp->para[0]), (bool) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((sdgeomfitter*) G__getstructoffset())->Ifit((Int_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((sdgeomfitter*) G__getstructoffset())->Ifit());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   sdgeomfitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new sdgeomfitter[n];
     } else {
       p = new((void*) gvp) sdgeomfitter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new sdgeomfitter;
     } else {
       p = new((void*) gvp) sdgeomfitter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->calcNewCore((rufptn_class*) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((sdgeomfitter*) G__getstructoffset())->compVars((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((sdgeomfitter*) G__getstructoffset())->compVars();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) sdgeomfitter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sdgeomfitter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) sdgeomfitter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      sdgeomfitter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((sdgeomfitter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sdgeomfitter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) sdgeomfitter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) sdgeomfitter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__sdgeomfitterDict_476_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) sdgeomfitter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__sdgeomfitterDict_476_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   sdgeomfitter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new sdgeomfitter(*(sdgeomfitter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef sdgeomfitter G__Tsdgeomfitter;
static int G__sdgeomfitterDict_476_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (sdgeomfitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((sdgeomfitter*) (soff+(sizeof(sdgeomfitter)*i)))->~G__Tsdgeomfitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (sdgeomfitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((sdgeomfitter*) (soff))->~G__Tsdgeomfitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__sdgeomfitterDict_476_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   sdgeomfitter* dest = (sdgeomfitter*) G__getstructoffset();
   *dest = *(sdgeomfitter*) libp->para[0].ref;
   const sdgeomfitter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* sdgeomfitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncsdgeomfitterDict {
 public:
  G__Sizep2memfuncsdgeomfitterDict(): p(&G__Sizep2memfuncsdgeomfitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncsdgeomfitterDict::*p)();
};

size_t G__get_sizep2memfuncsdgeomfitterDict()
{
  G__Sizep2memfuncsdgeomfitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancesdgeomfitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter))) {
     sdgeomfitter *G__Lderived;
     G__Lderived=(sdgeomfitter*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter),G__get_linked_tagnum(&G__sdgeomfitterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablesdgeomfitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Int_t> >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Int_t> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Double_t> >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Double_t> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Short_t> >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<short,allocator<short> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Short_t> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Char_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDEventSubData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Float_t> >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibHostData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibSubData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibWeatherData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevWeatherData_class>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* sdgeomfitter */
static void G__setup_memvarsdgeomfitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter));
   { sdgeomfitter *p; p=(sdgeomfitter*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->gMinuit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TMinuit),-1,-1,1,"gMinuit=",0,"Minuit fitter");
   G__memvar_setup((void*)((long)(&p->sdorigin_xy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"sdorigin_xy[2]=",0,"Position of SD origin with respect to CLF in CLF frame");
   G__memvar_setup((void*)((long)(&p->gTrsdVsR)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TGraphErrors),-1,-1,1,"gTrsdVsR=",0,"Time fit residual vs distance from core in ground plane");
   G__memvar_setup((void*)((long)(&p->gTrsdVsS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TGraphErrors),-1,-1,1,"gTrsdVsS=",0,"Time fit residual vs distance from shower axis");
   G__memvar_setup((void*)((long)(&p->gTvsU)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TGraphErrors),-1,-1,1,"gTvsU=",0,"Time vs distance along the shower axis in ground plane");
   G__memvar_setup((void*)((long)(&p->gQvsS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TGraphErrors),-1,-1,1,"gQvsS=",0,"Charge [VEM] vs Distance from Shower axis");
   G__memvar_setup((void*)((long)(&p->ngpts)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ngpts=",0,"rufptn indices of good points after cleaning");
   G__memvar_setup((void*)((long)(&p->goodpts)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"goodpts[1024]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hRsdS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TH2F),-1,-1,1,"hRsdS=",0,"Residuals vs S scatter plot");
   G__memvar_setup((void*)((long)(&p->pRsdS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TProfile),-1,-1,1,"pRsdS=",0,"Residuals vs S profile plot");
   G__memvar_setup((void*)((long)(&p->hRsdRho)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TH2F),-1,-1,1,"hRsdRho=",0,"Residuals vs rho scatter plot");
   G__memvar_setup((void*)((long)(&p->pRsdRho)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TProfile),-1,-1,1,"pRsdRho=",0,"Residuals vs rho profile plot");
   G__memvar_setup((void*)((long)(&p->theta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->phi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"phi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtheta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dtheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dphi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dphi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->R)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"R[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dR)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dR[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dT0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dT0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->a)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->da)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"da=",0,"Curvature parameter");
   G__memvar_setup((void*)((long)(&p->linsleyA)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"linsleyA=",0,"factor that goes into Linley's Time Delay function,");
   G__memvar_setup((void*)((long)(&p->chi2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"chi2=",0,"FCN at its minimum");
   G__memvar_setup((void*)((long)(&p->ndof)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndof=",0,"number of fit pts minus number of fit params");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"theta_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"phi_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"R_old[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("real8"),-1,4,"T0_old=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__sdgeomfitterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarsdgeomfitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncsdgeomfitter(void) {
   /* sdgeomfitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter));
   G__memfunc_setup("loadVariables_stclust",2218,G__sdgeomfitterDict_476_0_1, 103, -1, -1, 0, 2, 1, 1, 0, 
"U 'rufptn_class' - 0 - rufptn1 U 'rusdgeom_class' - 0 - rusdgeom1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("xycoor",676,G__sdgeomfitterDict_476_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - xxyy I - 'Int_t' 0 - xy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("cleanClust",1038,G__sdgeomfitterDict_476_0_3, 105, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '4.0' deltaChi2 g - - 0 'true' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("calcRsd",700,G__sdgeomfitterDict_476_0_4, 121, -1, -1, 0, 6, 1, 1, 0, 
"i - 'Int_t' 0 - ipoint D - 'Double_t' 0 - trsd "
"D - 'Double_t' 0 - terr D - 'Double_t' 0 - chrg "
"D - 'Double_t' 0 - rcore D - 'Double_t' 0 - score", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("cleanRsd",812,G__sdgeomfitterDict_476_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fillRsd",720,G__sdgeomfitterDict_476_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Ifit",396,G__sdgeomfitterDict_476_0_7, 103, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 '0' whatFCN g - - 0 'true' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sdgeomfitter",1293,G__sdgeomfitterDict_476_0_8, 105, G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("calcNewCore",1094,G__sdgeomfitterDict_476_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'rufptn_class' - 0 - pass1 D - 'Double_t' 0 - newCore", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compVars",843,G__sdgeomfitterDict_476_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' whatFCN", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("save_fpars",1066,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "to save fit parameters in a buffer", (void*) NULL, 0);
   G__memfunc_setup("restore_fpars",1407,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "to restore the fit parameters, so that they can be used as starting values", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__sdgeomfitterDict_476_0_13, 85, G__get_linked_tagnum(&G__sdgeomfitterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&sdgeomfitter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__sdgeomfitterDict_476_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sdgeomfitter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__sdgeomfitterDict_476_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&sdgeomfitter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__sdgeomfitterDict_476_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&sdgeomfitter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__sdgeomfitterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__sdgeomfitterDict_476_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__sdgeomfitterDict_476_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sdgeomfitter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__sdgeomfitterDict_476_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&sdgeomfitter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__sdgeomfitterDict_476_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&sdgeomfitter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__sdgeomfitterDict_476_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&sdgeomfitter::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("sdgeomfitter", 1293, G__sdgeomfitterDict_476_0_25, (int) ('i'), G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter), -1, 0, 1, 1, 1, 0, "u 'sdgeomfitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~sdgeomfitter", 1419, G__sdgeomfitterDict_476_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__sdgeomfitterDict_476_0_27, (int) ('u'), G__get_linked_tagnum(&G__sdgeomfitterDictLN_sdgeomfitter), -1, 1, 1, 1, 1, 0, "u 'sdgeomfitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncsdgeomfitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalsdgeomfitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcsdgeomfitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__sdgeomfitterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR = { "vector<char,allocator<char> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TMinuit = { "TMinuit" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR = { "vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR = { "vector<SDEventSubData_class,allocator<SDEventSubData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDEventSubData_class,allocator<SDEventSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR = { "vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR = { "vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR = { "vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR = { "vector<SDCalibevData_class,allocator<SDCalibevData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevData_class,allocator<SDCalibevData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR = { "vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_rufptn_class = { "rufptn_class" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_rusdgeom_class = { "rusdgeom_class" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TProfile = { "TProfile" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__sdgeomfitterDictLN_sdgeomfitter = { "sdgeomfitter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablesdgeomfitterDict() {
  G__sdgeomfitterDictLN_TClass.tagnum = -1 ;
  G__sdgeomfitterDictLN_TBuffer.tagnum = -1 ;
  G__sdgeomfitterDictLN_TMemberInspector.tagnum = -1 ;
  G__sdgeomfitterDictLN_TObject.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_TMinuit.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_rufptn_class.tagnum = -1 ;
  G__sdgeomfitterDictLN_rusdgeom_class.tagnum = -1 ;
  G__sdgeomfitterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__sdgeomfitterDictLN_TGraphErrors.tagnum = -1 ;
  G__sdgeomfitterDictLN_TProfile.tagnum = -1 ;
  G__sdgeomfitterDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__sdgeomfitterDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__sdgeomfitterDictLN_TH2F.tagnum = -1 ;
  G__sdgeomfitterDictLN_sdgeomfitter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablesdgeomfitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TMinuit);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_rufptn_class);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_rusdgeom_class);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TProfile);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_TH2F);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__sdgeomfitterDictLN_sdgeomfitter),sizeof(sdgeomfitter),-1,29952,(char*)NULL,G__setup_memvarsdgeomfitter,G__setup_memfuncsdgeomfitter);
}
extern "C" void G__cpp_setupsdgeomfitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupsdgeomfitterDict()");
  G__set_cpp_environmentsdgeomfitterDict();
  G__cpp_setup_tagtablesdgeomfitterDict();

  G__cpp_setup_inheritancesdgeomfitterDict();

  G__cpp_setup_typetablesdgeomfitterDict();

  G__cpp_setup_memvarsdgeomfitterDict();

  G__cpp_setup_memfuncsdgeomfitterDict();
  G__cpp_setup_globalsdgeomfitterDict();
  G__cpp_setup_funcsdgeomfitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncsdgeomfitterDict();
  return;
}
class G__cpp_setup_initsdgeomfitterDict {
  public:
    G__cpp_setup_initsdgeomfitterDict() { G__add_setup_func("sdgeomfitterDict",(G__incsetup)(&G__cpp_setupsdgeomfitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initsdgeomfitterDict() { G__remove_setup_func("sdgeomfitterDict"); }
};
G__cpp_setup_initsdgeomfitterDict G__cpp_setup_initializersdgeomfitterDict;

