//
// File generated by rootcint at Wed Sep  6 14:38:15 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dInetdIminusdIhomedIgrishadItadIsdanalysisdIsdatmdItmpdIatmparfitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "atmparfitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void atmparfitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_atmparfitter(void *p = 0);
   static void *newArray_atmparfitter(Long_t size, void *p);
   static void delete_atmparfitter(void *p);
   static void deleteArray_atmparfitter(void *p);
   static void destruct_atmparfitter(void *p);
   static void streamer_atmparfitter(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::atmparfitter*)
   {
      ::atmparfitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::atmparfitter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("atmparfitter", ::atmparfitter::Class_Version(), "/net/minus/home/grisha/ta/sdanalysis/sdatm/atmparfitter.h", 20,
                  typeid(::atmparfitter), DefineBehavior(ptr, ptr),
                  &::atmparfitter::Dictionary, isa_proxy, 0,
                  sizeof(::atmparfitter) );
      instance.SetNew(&new_atmparfitter);
      instance.SetNewArray(&newArray_atmparfitter);
      instance.SetDelete(&delete_atmparfitter);
      instance.SetDeleteArray(&deleteArray_atmparfitter);
      instance.SetDestructor(&destruct_atmparfitter);
      instance.SetStreamerFunc(&streamer_atmparfitter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::atmparfitter*)
   {
      return GenerateInitInstanceLocal((::atmparfitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::atmparfitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *atmparfitter::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *atmparfitter::Class_Name()
{
   return "atmparfitter";
}

//______________________________________________________________________________
const char *atmparfitter::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::atmparfitter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int atmparfitter::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::atmparfitter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void atmparfitter::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::atmparfitter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *atmparfitter::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::atmparfitter*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void atmparfitter::Streamer(TBuffer &R__b)
{
   // Stream an object of class atmparfitter.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> dateFrom;
      R__b >> dateTo;
      R__b >> yymmddFrom;
      R__b >> hhmmssFrom;
      R__b >> yymmddTo;
      R__b >> hhmmssTo;
      R__b >> gMoVsHderiv;
      R__b >> gPvsH;
      R__b >> fMoVsHderiv;
      R__b >> fMoVsH;
      R__b.CheckByteCount(R__s, R__c, atmparfitter::IsA());
   } else {
      R__c = R__b.WriteVersion(atmparfitter::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << dateFrom;
      R__b << dateTo;
      R__b << yymmddFrom;
      R__b << hhmmssFrom;
      R__b << yymmddTo;
      R__b << hhmmssTo;
      R__b << gMoVsHderiv;
      R__b << gPvsH;
      R__b << fMoVsHderiv;
      R__b << fMoVsH;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void atmparfitter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class atmparfitter.
      TClass *R__cl = ::atmparfitter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dateFrom", &dateFrom);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dateTo", &dateTo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "yymmddFrom", &yymmddFrom);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hhmmssFrom", &hhmmssFrom);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "yymmddTo", &yymmddTo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hhmmssTo", &hhmmssTo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gMoVsHderiv", &gMoVsHderiv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gPvsH", &gPvsH);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMoVsHderiv", &fMoVsHderiv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMoVsH", &fMoVsH);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_atmparfitter(void *p) {
      return  p ? new(p) ::atmparfitter : new ::atmparfitter;
   }
   static void *newArray_atmparfitter(Long_t nElements, void *p) {
      return p ? new(p) ::atmparfitter[nElements] : new ::atmparfitter[nElements];
   }
   // Wrapper around operator delete
   static void delete_atmparfitter(void *p) {
      delete ((::atmparfitter*)p);
   }
   static void deleteArray_atmparfitter(void *p) {
      delete [] ((::atmparfitter*)p);
   }
   static void destruct_atmparfitter(void *p) {
      typedef ::atmparfitter current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_atmparfitter(TBuffer &buf, void *obj) {
      ((::atmparfitter*)obj)->::atmparfitter::Streamer(buf);
   }
} // end of namespace ROOT for class ::atmparfitter

/********************************************************
* /net/minus/home/grisha/ta/sdanalysis/sdatm/tmp/atmparfitterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableatmparfitterDict();

extern "C" void G__set_cpp_environmentatmparfitterDict() {
  G__cpp_reset_tagtableatmparfitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevatmparfitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* atmparfitter */
static int G__atmparfitterDict_512_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->loadVariables((gdas_dst_common*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->loadVariables((gdas_class*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->loadFromRhoVsHgraph((TGraph*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->loadFromRhoVsHgraphWerr((TGraphErrors*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->put2atmpar((atmpar_dst_common*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->put2atmpar((atmpar_class*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((atmparfitter*) G__getstructoffset())->GetMoVsHderiv());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((atmparfitter*) G__getstructoffset())->GetPvsH());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((atmparfitter*) G__getstructoffset())->GetMoVsHderivfit());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((atmparfitter*) G__getstructoffset())->GetMoVsH());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->Fit((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((atmparfitter*) G__getstructoffset())->Fit());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   atmparfitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new atmparfitter[n];
     } else {
       p = new((void*) gvp) atmparfitter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new atmparfitter;
     } else {
       p = new((void*) gvp) atmparfitter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) atmparfitter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) atmparfitter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) atmparfitter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      atmparfitter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((atmparfitter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) atmparfitter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) atmparfitter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) atmparfitter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__atmparfitterDict_512_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) atmparfitter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__atmparfitterDict_512_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   atmparfitter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new atmparfitter(*(atmparfitter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef atmparfitter G__Tatmparfitter;
static int G__atmparfitterDict_512_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (atmparfitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((atmparfitter*) (soff+(sizeof(atmparfitter)*i)))->~G__Tatmparfitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (atmparfitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((atmparfitter*) (soff))->~G__Tatmparfitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__atmparfitterDict_512_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   atmparfitter* dest = (atmparfitter*) G__getstructoffset();
   *dest = *(atmparfitter*) libp->para[0].ref;
   const atmparfitter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* atmparfitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncatmparfitterDict {
 public:
  G__Sizep2memfuncatmparfitterDict(): p(&G__Sizep2memfuncatmparfitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncatmparfitterDict::*p)();
};

size_t G__get_sizep2memfuncatmparfitterDict()
{
  G__Sizep2memfuncatmparfitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceatmparfitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter))) {
     atmparfitter *G__Lderived;
     G__Lderived=(atmparfitter*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter),G__get_linked_tagnum(&G__atmparfitterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableatmparfitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("atmpar_dst_common",117,G__get_linked_tagnum(&G__atmparfitterDictLN_atmpar_dst_common),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("gdas_dst_common",117,G__get_linked_tagnum(&G__atmparfitterDictLN__fdatmos_param_t),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Int_t> >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Int_t> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Double_t> >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Double_t> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Short_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Short_t> >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<short,allocator<short> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<Short_t> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Char_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDEventSubData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<Float_t> >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<float,allocator<float> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibHostData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibSubData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibWeatherData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SDCalibevWeatherData_class>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<UShort_t> >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned short,allocator<unsigned short> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<UShort_t> > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > > >",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Byte_t>",117,G__get_linked_tagnum(&G__atmparfitterDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* atmparfitter */
static void G__setup_memvaratmparfitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter));
   { atmparfitter *p; p=(atmparfitter*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->dateFrom)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"dateFrom=",0,"date range, sec since 1970/1/1");
   G__memvar_setup((void*)((long)(&p->dateTo)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"dateTo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->yymmddFrom)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"yymmddFrom=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hhmmssFrom)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hhmmssFrom=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->yymmddTo)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"yymmddTo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hhmmssTo)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hhmmssTo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__atmparfitterDictLN_TGraphErrors),-1,-1,4,"gMoVsHderiv=",0,"density [g/cm^3] vs height [cm]");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__atmparfitterDictLN_TGraph),-1,-1,4,"gPvsH=",0,"pressure [Pa] vs height [cm]");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__atmparfitterDictLN_TF1),-1,-1,4,"fMoVsHderiv=",0,"fit function for density vs height");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__atmparfitterDictLN_TF1),-1,-1,4,"fMoVsH=",0,"vertical mass overburden vs height");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__atmparfitterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvaratmparfitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncatmparfitter(void) {
   /* atmparfitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter));
   G__memfunc_setup("loadVariables",1337,G__atmparfitterDict_512_0_1, 103, -1, -1, 0, 1, 1, 1, 0, "U '_fdatmos_param_t' 'gdas_dst_common' 0 - gdas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadVariables",1337,G__atmparfitterDict_512_0_2, 103, -1, -1, 0, 1, 1, 1, 0, "U 'gdas_class' - 0 - gdas", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadFromRhoVsHgraph",1920,G__atmparfitterDict_512_0_3, 103, -1, -1, 0, 1, 1, 1, 0, "U 'TGraph' - 0 - g_rho_vs_h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("loadFromRhoVsHgraphWerr",2336,G__atmparfitterDict_512_0_4, 103, -1, -1, 0, 1, 1, 1, 0, "U 'TGraphErrors' - 0 - g_rho_vs_h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("put2atmpar",1040,G__atmparfitterDict_512_0_5, 103, -1, -1, 0, 1, 1, 1, 0, "U 'atmpar_dst_common' 'atmpar_dst_common' 0 - atmpar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("put2atmpar",1040,G__atmparfitterDict_512_0_6, 103, -1, -1, 0, 1, 1, 1, 0, "U 'atmpar_class' - 0 - atmpar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMoVsHderiv",1287,G__atmparfitterDict_512_0_7, 85, G__get_linked_tagnum(&G__atmparfitterDictLN_TGraphErrors), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPvsH",673,G__atmparfitterDict_512_0_8, 85, G__get_linked_tagnum(&G__atmparfitterDictLN_TGraph), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMoVsHderivfit",1610,G__atmparfitterDict_512_0_9, 85, G__get_linked_tagnum(&G__atmparfitterDictLN_TF1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMoVsH",749,G__atmparfitterDict_512_0_10, 85, G__get_linked_tagnum(&G__atmparfitterDictLN_TF1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Fit",291,G__atmparfitterDict_512_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' verbose", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("atmparfitter",1299,G__atmparfitterDict_512_0_12, 105, G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__atmparfitterDict_512_0_13, 85, G__get_linked_tagnum(&G__atmparfitterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&atmparfitter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__atmparfitterDict_512_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&atmparfitter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__atmparfitterDict_512_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&atmparfitter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__atmparfitterDict_512_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&atmparfitter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__atmparfitterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__atmparfitterDict_512_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__atmparfitterDict_512_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&atmparfitter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__atmparfitterDict_512_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&atmparfitter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__atmparfitterDict_512_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&atmparfitter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__atmparfitterDict_512_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&atmparfitter::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("atmparfitter", 1299, G__atmparfitterDict_512_0_25, (int) ('i'), G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter), -1, 0, 1, 1, 1, 0, "u 'atmparfitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~atmparfitter", 1425, G__atmparfitterDict_512_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__atmparfitterDict_512_0_27, (int) ('u'), G__get_linked_tagnum(&G__atmparfitterDictLN_atmparfitter), -1, 1, 1, 1, 1, 0, "u 'atmparfitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncatmparfitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalatmparfitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcatmparfitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__atmparfitterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR = { "vector<char,allocator<char> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_atmpar_dst_common = { "atmpar_dst_common" , 115 , -1 };
G__linked_taginfo G__atmparfitterDictLN__fdatmos_param_t = { "_fdatmos_param_t" , 115 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >,allocator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR = { "vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > >,allocator<vector<vector<short,allocator<short> >,allocator<vector<short,allocator<short> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR = { "vector<SDEventSubData_class,allocator<SDEventSubData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDEventSubData_class,allocator<SDEventSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR = { "vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR = { "vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibHostData_class,allocator<SDCalibHostData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR = { "vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibSubData_class,allocator<SDCalibSubData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR = { "vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibWeatherData_class,allocator<SDCalibWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR = { "vector<SDCalibevData_class,allocator<SDCalibevData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevData_class,allocator<SDCalibevData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR = { "vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SDCalibevWeatherData_class,allocator<SDCalibevWeatherData_class> >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_atmpar_class = { "atmpar_class" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR = { "vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > >,allocator<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > > > >" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > >,allocator<vector<vector<unsigned short,allocator<unsigned short> >,allocator<vector<unsigned short,allocator<unsigned short> > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_gdas_class = { "gdas_class" , 99 , -1 };
G__linked_taginfo G__atmparfitterDictLN_atmparfitter = { "atmparfitter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableatmparfitterDict() {
  G__atmparfitterDictLN_TClass.tagnum = -1 ;
  G__atmparfitterDictLN_TBuffer.tagnum = -1 ;
  G__atmparfitterDictLN_TMemberInspector.tagnum = -1 ;
  G__atmparfitterDictLN_TObject.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_atmpar_dst_common.tagnum = -1 ;
  G__atmparfitterDictLN__fdatmos_param_t.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_atmpar_class.tagnum = -1 ;
  G__atmparfitterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__atmparfitterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__atmparfitterDictLN_TF1.tagnum = -1 ;
  G__atmparfitterDictLN_TGraph.tagnum = -1 ;
  G__atmparfitterDictLN_TGraphErrors.tagnum = -1 ;
  G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__atmparfitterDictLN_gdas_class.tagnum = -1 ;
  G__atmparfitterDictLN_atmparfitter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableatmparfitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEcharcOallocatorlEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_atmpar_dst_common);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN__fdatmos_param_t);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEshortcOallocatorlEshortgRsPgRcOallocatorlEvectorlEshortcOallocatorlEshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDEventSubData_classcOallocatorlESDEventSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibHostData_classcOallocatorlESDCalibHostData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibSubData_classcOallocatorlESDCalibSubData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibWeatherData_classcOallocatorlESDCalibWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevData_classcOallocatorlESDCalibevData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlESDCalibevWeatherData_classcOallocatorlESDCalibevWeatherData_classgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_atmpar_class);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TF1);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TGraph);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_vectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_gdas_class);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__atmparfitterDictLN_atmparfitter),sizeof(atmparfitter),-1,29952,(char*)NULL,G__setup_memvaratmparfitter,G__setup_memfuncatmparfitter);
}
extern "C" void G__cpp_setupatmparfitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupatmparfitterDict()");
  G__set_cpp_environmentatmparfitterDict();
  G__cpp_setup_tagtableatmparfitterDict();

  G__cpp_setup_inheritanceatmparfitterDict();

  G__cpp_setup_typetableatmparfitterDict();

  G__cpp_setup_memvaratmparfitterDict();

  G__cpp_setup_memfuncatmparfitterDict();
  G__cpp_setup_globalatmparfitterDict();
  G__cpp_setup_funcatmparfitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncatmparfitterDict();
  return;
}
class G__cpp_setup_initatmparfitterDict {
  public:
    G__cpp_setup_initatmparfitterDict() { G__add_setup_func("atmparfitterDict",(G__incsetup)(&G__cpp_setupatmparfitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initatmparfitterDict() { G__remove_setup_func("atmparfitterDict"); }
};
G__cpp_setup_initatmparfitterDict G__cpp_setup_initializeratmparfitterDict;

